# Generated by Django 4.2.27 on 2026-01-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'teacher', 'day_of_week', 'period_slot'], name='timetable_e_timetab_bc7fab_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'section', 'day_of_week', 'period_slot'], name='timetable_e_timetab_0c92f3_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'room', 'day_of_week', 'period_slot'], name='timetable_e_timetab_842285_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'day_of_week'], name='timetable_e_timetab_0931ed_idx'),
        ),
    ]
