# Generated by Django 4.2.27 on 2026-01-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_allow_null_teacher_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='departure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
